'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import '@mantine/core/styles.css';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Clickable Overhead',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}><MantineProvider>{children}</MantineProvider></body>
    </html>
  )
}
