import './globals.css'
import '@mantine/notifications/styles.css';
import { Inter } from 'next/font/google'
import '@mantine/core/styles.css';
import { ColorSchemeScript } from '@mantine/core';
import { Providers } from './providers';
import { Notifications } from '@mantine/notifications';


export const metadata = {
  title: 'Clickable Overhead',
  description: 'Generated by create next app',
}


const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}><Providers><Notifications />
{children}</Providers></body>
    </html>
  )
}
