import './globals.css'
import { Inter } from 'next/font/google'
import '@mantine/core/styles.css';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import { Providers } from './providers';
import { Notifications } from '@mantine/notifications';


export const metadata = {
  title: 'Clickable Overhead',
  description: 'Generated by create next app',
}


const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <Notifications />
      </head>
      <body className={inter.className}><MantineProvider><Providers>{children}</Providers></MantineProvider></body>
    </html>
  )
}
